const TYPES_OF_BLOCKS = 2;
const BLOCKS_PER_ROW = 8;
const TOTAL_BLOCKS = 64;
const RED_PIECE_END_BLOCK = 24;
const BLACK_PIECE_START_BLOCK = 40;
const BLACK_PIECE_CAPTURE_LIMIT = 16;
const RED_PIECE_CAPTURE_LIMIT = 48;

const RED_PIECE = 'red';
const BLACK_PIECE = 'black';
const NO_PIECE = 'none';
